### PR TITLE
[WIP] Run content through doctoc --maxlevel 3

### PR DESCRIPTION
**Pull request by sdodson**
Don't intend to merge this, just putting this out there for review, we can use doctoc to manage the TOC if we adjust the heading levels according to our desire for an item to show up in the TOC or not.

```
sudo npm install -g doctoc
doctoc --maxlevel 3 --github beta-3-setup.md
```

### CODE REVIEW

**Comment by thoraxe** [comment]
Sounds cool to me. It looks like this one needs a rebase but I would be happy to use this.

**Comment by sdodson** [comment]
If we do this, I think we should readjust some of the header levels.

# Title
# Setup
## yatta
## 
# Examples
## yatta yatta
# Appendices
## you guessed it

**Comment by thoraxe** [comment]
What do I need to be able to use "npm"? I should probably do "doctoc" myself...

**Comment by sdodson** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

Install the npm rpm, for RHEL7 it's in epel.

On 04/27/2015 09:05 PM, Erik M Jacobs wrote:

> What do I need to be able to use "npm"? I should probably do
> "doctoc" myself...
> 
> --- Reply to this email directly or view it on GitHub: 
> https://github.com/openshift/training/pull/121#issuecomment-96864324
> 
> -----BEGIN PGP SIGNATURE-----
> Version: GnuPG v2.0.22 (GNU/Linux)

iQEcBAEBAgAGBQJVP4eKAAoJEMRr2CP2Mq29Et0H/R/9j24lbL5zY2FBNDTWQaoQ
QeHkikxbc6gB9b08OyxUnGSTkHnjV+B12FI/w2zUWt3SRXzsevpt3bMMqdEA5HsN
LrOyhofleSViEXEmb9ghlsHvDfxzGQE+eI8hyDxTt3KdrTNODvmQHcg8mgOye4Pa
BfxOc+ozeDzBafaDO1I0PRzYxBVI2zUyaoI/Ek4EOB3JCPIoOSAwpWw1xwkSe2Us
2oHtbbvQ8mNDPe2D9hjnFgvuiA8X01q0xH7MyDTsiciqWcG2poxnoUX42dm1ke1y
GGd8GSM/njQLClIWb9VRrs0Si6GFM4Vbrk05GE6TJn15cxW+vX2wZ4VlK4SSPbY=
=US3P
-----END PGP SIGNATURE-----

**Comment by thoraxe** [comment]
Running this myself now.

**Pull request closed without merging**
