### PR TITLE
Add Appendix and ansible playbooks for configuring AWS deployments

### PR DESCRIPTION
**Pull request by detiber**

### CODE REVIEW

**Comment by thoraxe** [comment]
So this is a dumb question -- is there a reason we have so many of these files in the training repo as opposed to using them out of the openshift-ansible repo?

I can't tell if these are customized for our targeted training environment or not.

**Comment by detiber** [comment]
@thoraxe currently, yes they are tweaked a bit to work for the installer use case (and enterprise in general).

For example the following things are done, which are not done in the openshift-ansible playbooks (yet).
1. The hosts are registered to rhsm and subscribed to the beta channel
2. aws security groups are created and are configured with the proper port settings.
3. The way the ec2 hosts are spun up is differently (using an exact count for the number of master/node instances), where we just spin up a certain number of hosts.

I'm also working on a fix which would create route53 records for the hosts as well (and the app domain).  

Eventually, I'll work all of these back into openshift-ansible, it's just not a trivial change and it would have to be generalized enough to work with multiple providers.

**Comment by detiber** [comment]
@thoraxe also, I'm wrapping up the route53 changes, so once I have those, I'll rebase the PR so that it is merge-able again.

**Comment by thoraxe** [comment]
I guess I was looking more for information on any tweaks required to make the existing installer work on AWS (eg: public vs. private hostname), as opposed to making the installer actually set up AWS for you.

Not that your work is in vain -- it's awesome. I think I just wasn't expecting that much.

We definitely need to know (document) how to tweak the BYO installer to run on AWS, and then I guess separately how to use the AWS-specific installer to provision the $WHOLETHING... ?

**Comment by detiber** [comment]
@thoraxe I tried to accomplish that with the 'Generic cloud install' section of the appendix, the aws script was more just a bonus (and me testing around with getting some of that stuff working in prep for openshift-ansible)

**Comment by detiber** [comment]
@thoraxe rebased on master.  I tried to run doctoc to update the TOC, but for some reason it wanted to delete the other Appendices from the TOC.

**Comment by detiber** [comment]
@thoraxe, also route53 support has now been added (for pre-existing hosted zones in aws).

**Comment by thoraxe** [comment]
You were missing some closing ticks and I generally dislike the ticks in markdown so I cleaned it up.

**Pull request merged**
