### PR TITLE
Update expected haproxy routes.json

### PR DESCRIPTION
**Pull request by sosiouxme**
I think the format has changed since this was written. Check for yourself... this is what mine looks like:

```
  "hello-openshift-service": {
    "Name": "hello-openshift-service",
    "EndpointTable": {
      "10.1.0.19:8080": {
        "ID": "10.1.0.19:8080",
        "IP": "10.1.0.19",
        "Port": "8080"
      }
    },
    "ServiceAliasConfigs": {
      "hello-openshift.cloudapps.example.com-": {
        "Host": "hello-openshift.cloudapps.example.com",
        "Path": "",
        "TLSTermination": "",
        "Certificates": null
      }
    }
  },
```

### CODE REVIEW

**Comment by thoraxe** [comment]
So, the current configuration still works just fine. I worry about the endpointtable entries because I don't know of any way to actually find the endpoint information. One of the `osc` commands to get that info didn't make it into a rebase, and I'm not sure it's even still there.

I'm sure that there are newer versions, but I'd like to stick with what we have for beta1 if there are no objections.

**Comment by sosiouxme** [comment]
This is just what the current beta1 router component generates in its routes.json. I'm just reporting what I see :) which is different from what the doc tells users to expect. Always possible I've borked something in my personal install...

**Comment by thoraxe** [comment]
Sorry, I misunderstood what you are saying.

What you are saying is that the JSON you pasted is the data that is contained inside the router -- not the route definition.

Right?

**Comment by sosiouxme** [comment]
Right, exactly.

Too much JSON flying around...

**Pull request merged**
