### PR TITLE
Update toc

### PR DESCRIPTION
**Pull request by nak3**
Update TOC

### CODE REVIEW

**Comment by sosiouxme** [comment]
I haven't gone through the TOC and checked it against the newest from beta3, just added entries as I added topics. So there could be some gaps.

It's not the intent that every single subtitle should be in the TOC. It is very long already so unless a subtitle is something I think someone will look for, I would advocate leaving it out. We can, of course, discuss that decision if you think it's too confusing for some to be arbitrarily missing.

**Comment by sosiouxme** [comment]
Guessing you didn't mean to include  beta-3-setup.md.update

**Comment by nak3** [comment]
I understand. The reason why I updated to TOC is that many people will compare beta2 to beta3 by TOC. But after I re-check the TOC, I understand you added minimum but enough topics.

However, the section of "STI - What Is It?" should be updated because some contents have dead links.
(eg. Switch contexts, A Simple STI Build, Create the Build Process)

Please close this PR. This includes too many waste commits. 

PS. Yes,I didn't mean to include `beta-3-setup.md.update`.

**Comment by sosiouxme** [comment]
We definitely want to fix dead links. And we definitely need to take a final pass through the TOC to make sure it matches the contents.

**Comment by nak3** [comment]
New [pull/120](https://github.com/openshift/training/pull/120) looks good.
I close this PR.
Thank you @sosiouxme

**Pull request closed without merging**
