### PR TITLE
some changes I did during my tests of GA codebase

### PR DESCRIPTION
**Pull request by juhoffma**
Hi Erik,

I started off with a GA Installation and tried to use some of the beta4 files, but there were some errors on the way, which I started fixing. Hopefully we can collaborate on this stuff. Hopefully I am not breaking anything you have done before. I have started copying everything from the beta4 directory to the _new_ GA directory and added my files.

Buddy

### CODE REVIEW

**Comment by thoraxe** [comment]
Well, I have my own GA branch here:

https://github.com/thoraxe/training/tree/GA-work

I hope we aren't duplicating each other's work here.

Maybe you can try to rebase against my GA branch? I hadn't committed anything to the main OpenShift repo but I guess I should. I'll try to do that later tonight.

**Comment by sdodson** [comment]
@thoraxe do we know the fate of the training repo? Is it something that's to be maintained long term or should everything here be moved into docs as task based documentation?

**Comment by thoraxe** [comment]
The plan is for me to keep it up to date, but I've been travelling 100% through Summit and just haven't had a chance to do anything.

I am hoping to do some work on it next week while I'm in Germany doing training.

**Comment by sdodson** [comment]
Erik,

Ok, I'll try to do a run through of your GA branch if I get time. Even if
there are rough edges I think we should update training with GA content as
its current state most things don't work with GA bits.

**Comment by thoraxe** [comment]
The GA-work branch in my repo is up to date with GA based on whatever my commit is. I believe I said "finished through blahblah".

A lot of it is either updating JSON to say "v1" in stead of "v1beta3" and small tweaks to JSON format, and maybe changing a few command line references here and there.

Once my thing is merged we can probably merge THIS PR #295 to catch things that I missed, and be in good shape.

I don't plan to add a lot to the material other than maybe putting one of the primary nodes into maintenance, and maybe an example of using a secret or something. That's about it.

**Comment by thoraxe** [comment]
I just merged my GA-work into this repo's GA branch.

@juhoffma can you remove anything installation-based from your PR? We are going to remove all the installer stuff from the training repo and resort to pointing people at the new installer which won't require any files locally. For other installations we'll point directly at the openshift-ansible repo (eg: AWS, advanced, etc).

**Comment by juhoffma** [comment]
Hi Erik,

sure thing, will do, but will need to wait to some time next week.

Buddy

**Pull request closed without merging**
