### PR TITLE
Use "openshift ex config" for namespaces

### PR DESCRIPTION
**Pull request by sosiouxme**
It's a pain to have to add `--namespace=` or `-n <foo>` on everything. It's also really confusing when you forget to.

`osc namespace` went away, but we definitely don't plan for users to be adding `--namespace` everywhere for GA. The currently-available `openshift ex config` commands should be similar at least in concept to what we end up with. Since the beta at least is fairly frozen, I suggest we use this command.

### CODE REVIEW

**Comment by thoraxe** [comment]
Looks good but I just made changes so can you re-merge your end and re-pr?

**Comment by sosiouxme** [comment]
I already did once :) But OK, you made a lot more changes. I'll update this PR.

**Comment by thoraxe** [comment]
Things move fast around here! :)

**Comment by sosiouxme** [comment]
Alright I think it's ready.

**Pull request merged**
