### PR TITLE
Certs have moved to /etc/openshift/master/ in beta4

### PR DESCRIPTION
**Pull request by sdodson**

### CODE REVIEW

**Comment by sdodson** [comment]
@detiber fyi since I think you were looking at auto creating registry/router

**Comment by detiber** [comment]
@sdodson we'll probably end up using the config in ~/.config/openshift/.config for generating the registry/router, so this should not affect that.

**Comment by thoraxe** [comment]
Needs a rebase.

**Comment by sdodson** [comment]
Rebased'ish also fixed a bunch of /etc/openshift/master.yaml

**Pull request merged**
