### PR TITLE
Adding troubleshooting note about endpoints

### PR DESCRIPTION
**Pull request by brenton**

### CODE REVIEW

**Comment by thoraxe** [comment]
Can you add that to beta-2 as well?

**Comment by brenton** [comment]
Update!  I fixed the formatting too because I was previously creating a needless bullet.

**Comment by thoraxe** [comment]
Looks like this needs a re-look due to recent changes I've made. Sorry! :(

**Comment by brenton** [comment]
np, I'll rebase

**Comment by brenton** [comment]
@thoraxe, rebased...

**Pull request merged**
