### PR TITLE
Router service name workaround for wiring example

### PR DESCRIPTION
**Pull request by brenton**

### CODE REVIEW

**Comment by brenton** [comment]
For what it's worth you don't have to change the selectors.  They are properly namespaced, as well as the auto creation of the `DATABASE_SERVICE_HOST` environment variable the application relies on.

**Comment by thoraxe** [comment]
Is this still required based on @abhgupta and the pending merge of some commit?

**Comment by abhgupta** [comment]
@thoraxe the fix has already been merged and is in master - we are currently trying to see if we can cherry-pick it for beta2. Regardless, this change would not hurt and insulates us from any potential edge cases.

**Comment by thoraxe** [comment]
@brenton can you update the pr to include a change to "wiringbackend" too, or whatever?

**Comment by brenton** [comment]
The backend doesn't need to be renamed since it doesn't have a route.  I think we're just going to cherry-pick the real fix this morning.

**Comment by thoraxe** [comment]
OK I'll wait until the next build before closing or merging.

**Comment by thoraxe** [comment]
So, I haven't run into this yet... should we close or what? @brenton

**Pull request closed without merging**
