### PR TITLE
Note the registry can take a while to come up.

### PR DESCRIPTION
**Pull request by sosiouxme**
Especially if we give them the wrong name to pre-pull...

### CODE REVIEW

**Comment by sosiouxme** [comment]
P.S. @brenton said it's docker-registry for now. Would make sense to me to change that to ose-docker-registry for beta2.

**Comment by thoraxe** [comment]
Why do you say "the image needs to download"? That's the purpose of the pre-fetch?

**Comment by sosiouxme** [comment]
True, that's from when it was not pre-fetching with the right name and I was wondering why it took so long. I reworded all that.

**Comment by thoraxe** [comment]
RCM has renamed it "ose-docker-registry", and it worked in beta1. so I'm not sure what this PR does?

**Comment by thoraxe** [comment]
@sosiouxme registry.access has "ose-docker-registry"...

**Comment by sosiouxme** [comment]
Don't worry about it, I'll re-raise it if it still seems like an issue.

**Pull request closed without merging**
