### PR TITLE
Fix several typos and wording

### PR DESCRIPTION
**Pull request by runcom**
Signed-off-by: Antonio Murdaca runcom@redhat.com

### CODE REVIEW

**Comment by thoraxe** [comment]
Would you please re-evaluate this PR for the 31 changes.

**Comment by runcom** [comment]
sure

**Comment by runcom** [comment]
@thoraxe Rebased and updated, please take another look (I've fixed other typos I found also)

**Comment by thoraxe** [comment]
LGTM. Thanks for the work.

**Pull request merged**
