### PR TITLE
Update to v0.4 in the pre-fetch section, use normal --images format

### PR DESCRIPTION
**Pull request by sdodson**

### CODE REVIEW

**Comment by thoraxe** [comment]
I think my latest pushes have this change?

**Comment by sdodson** [comment]
Nah, you're still explicitly defining the image version in the `ex router` and `ex registry` commands.

**Comment by thoraxe** [comment]
have you tried it with the single quote? does it work?

**Comment by sdodson** [comment]
Yes, that's how i ran through the training. With double quotes bash interprets ${component} and ${version} so we must use single quotes.

**Pull request merged**
