### PR TITLE
Adding a note about repository naming

### PR DESCRIPTION
**Pull request by brenton**
@thoraxe, we had a few customers ask about this and it resulted in a bit of confusion.  After talking with RCM the decision was to fix the naming at GA and to document it for now.  Is this OK with you?

Also, I'll put this on the master branch if you're cool it with.

### CODE REVIEW

**Comment by thoraxe** [comment]
Is the concern that the "real" channel will be "rhel-7-server..." as opposed to "rhel-server-7..." ?

**Comment by sdodson** [comment]
It seems some folks were picking up that the naming of the beta channel was dissimilar from the other channels and were changing it rather than copying/pasting it directly.

The GA channel will be named 'rhel-7-server-ose-rpms' I imagine.

**Comment by thoraxe** [comment]
Ack. Can you rebase and also change the beta-3 setup?

**Comment by thoraxe** [comment]
Did you ever rebase this or issue a new PR for the beta3?

**Comment by thoraxe** [comment]
@brenton

**Comment by brenton** [comment]
Sorry, I lost track of this.  I rebased it so I'll merge it in to beta4.  Seems too late for beta3 now.

**Pull request merged**
