### PR TITLE
The template and script handles setting OPENSHIFT_MASTER based on KUBERNETES_MASTER

### PR DESCRIPTION
**Pull request by sdodson**
The template and script handles setting OPENSHIFT_MASTER based on KUBERNETES_MASTER therefore it's not necessary to modify the template.

### CODE REVIEW

**Comment by thoraxe** [comment]
You sure? :)

**Comment by sdodson** [comment]
I was wrong, it uses CONTAINER_ACCESSIBLE_API_HOST to configure the registry. KUBERNETES_MASTER is exported for benefit of running osc and probably un-necessary if you've already exported KUBECONFIG

I modified install-router.sh to just process the template and you can see that it's populating the registry's OPENSHIFT_MASTER with the value of CONTAINER_ACCESSIBLE_API_HOST

```
[root@openshift-master training]# git diff
diff --git a/install-registry.sh b/install-registry.sh
old mode 100644
new mode 100755
index 9734058..65de7ea
--- a/install-registry.sh
+++ b/install-registry.sh
@@ -40,4 +40,5 @@ export KUBERNETES_MASTER

 # Deploy private docker registry
 echo "[INFO] Submitting docker-registry template file for processing"
-osc process -f docker-registry-template.json -v "OPENSHIFT_MASTER=$API_SCHEME://${CONTAINER_ACCESSIBLE_API_HOST}:${API_PORT},OPENSHIFT_CA_DATA=${OPENSHIFT_CA_DATA},OPENSHIFT_CERT_DATA=${OPENSHIFT_CERT_DATA},OPENSHIFT_KEY_DATA=${OPENSHIFT_KEY_DATA}" | osc apply -f -
+osc process -f docker-registry-template.json -v "OPENSHIFT_MASTER=$API_SCHEME://${CONTAINER_ACCESSIBLE_API_HOST}:${API_PORT},OPENSHIFT_CA_DATA=${OPENSHIFT_CA_DATA},OPENSHIFT_CERT_DATA=${OPENSHIFT_CERT_DATA},OPENSHIFT_KEY_DATA=${OPENSHIFT_KEY_DATA}" 
+# | osc apply -f -
[root@openshift-master training]# CERT_DIR=/var/lib/openshift/openshift.local.certificates/master KUBERNETES_MASTER=https://openshift-master:8443 CONTAINER_ACCESSIBLE_API_HOST=openshift-master ./install-registry.sh > install-registry.json
[root@openshift-master training]# less install-registry.json 
[root@openshift-master training]# CERT_DIR=/var/lib/openshift/openshift.local.certificates/master KUBERNETES_MASTER=https://master-master-master:8443 CONTAINER_ACCESSIBLE_API_HOST=api-master ./install-registry.sh > install-registry.json.2
[root@openshift-master training]# diff -uw install-registry.json install-registry.json.2 
--- install-registry.json   2015-02-11 16:50:41.045260801 -0500
+++ install-registry.json.2 2015-02-11 16:51:36.829952330 -0500
@@ -89,7 +89,7 @@
                                             {
                                                 "name": "OPENSHIFT_MASTER",
                                                 "key": "OPENSHIFT_MASTER",
-                                                "value": "https://openshift-master:8443"
+                                                "value": "https://api-master:8443"
                                             },
                                             {
                                                 "name": "OPENSHIFT_CA_DATA",
```

**Comment by thoraxe** [comment]
OK, so we can safely delete modifying the registry template because the script will populate it from the env vars?

**Comment by sdodson** [comment]
Right, osc process -v sets/overrides the parameter values in the template.

**Comment by thoraxe** [comment]
Taking your word for it! :)

**Pull request merged**
