### PR TITLE
 reorg for placing infrastructure components

### PR DESCRIPTION
**Pull request by sosiouxme**
First draft, more to do, just wanted it to be visible already.

### CODE REVIEW

**Comment by thoraxe** [comment]
If you feel comfortable merging this go ahead. I don't mind having WIP in the non-master.

**Comment by sosiouxme** [comment]
I haven't actually tested this :)  I'll do a test run in the morning but I think it's close enough to merge.

(I don't have merge here...)

**Comment by thoraxe** [comment]
Do you want me to merge yet?

**Comment by sosiouxme** [comment]
Guess I'll have to rebase first. S'ok, have fixes anyway.

**Pull request merged**
