### PR TITLE
Adding docs on proxying imagestream imports

### PR DESCRIPTION
**Pull request by brenton**
@thoraxe, let me know if this looks OK and I'll put it on master too.  This process was provided by a customer.

### CODE REVIEW

**Comment by brenton** [comment]
Thinking more about the merge.  I think it would be better to create this PR against master and then merge master in to beta4 again.

**Comment by brenton** [comment]
actually, NM I forgot the traing for beta3 and beta4 are in different files.  I'll basically have to dual commit one way or another.

**Comment by thoraxe** [comment]
OK I will wait for you to rebase this with an update to the beta3 stuff also.

**Comment by brenton** [comment]
done.

**Pull request merged**
