### PR TITLE
Mention openshift-diagnostics in troubleshooting

### PR DESCRIPTION
**Pull request by sosiouxme**

### CODE REVIEW

**Comment by thoraxe** [comment]
Are you going to do one for beta4 also?

**Comment by sosiouxme** [comment]
Yes, but messaging will be different. Once diagnostics merges upstream it will be in the product, so users can just use that. Further checks added during beta4 can be released through the same side mechanism though.

**Comment by thoraxe** [comment]
OK so can you just put a placeholder+note in beta4 for the diag stuff so that I know not to copy-merge it?

**Comment by sosiouxme** [comment]
Sure, https://github.com/openshift/training/pull/178

**Pull request merged**
