### PR TITLE
Install ansible-1.8.4-1.el7

### PR DESCRIPTION
**Pull request by sdodson**

### CODE REVIEW

**Comment by sdodson** [comment]
@detiber does this make sense at this point in time?

**Comment by thoraxe** [comment]
Is this a requirement?

**Comment by sdodson** [comment]
My understanding is that 1.9.0.1 is bustificated, though there may be a better way to approach this.

**Comment by detiber** [comment]
@thoraxe yes, 1.8.4 is needed until 1.9.1 is released...  see: https://github.com/ansible/ansible/pull/10639

**Pull request merged**
