### PR TITLE
Updated beta3 docs to add new imagestreams and secret

### PR DESCRIPTION
**Pull request by sabre1041**
Updated steps to utilize the imagestream found in the jboss-openshift application template image streams
- Minor syntax corrections
- Instructions for adding imagestreams
- Instructions for adding secret

### CODE REVIEW

**Comment by sdodson** [comment]
This works in beta3? If it requires a release newer than v0.4.3 then we should make these changes against beta-4-setup.md in the beta4 branch.

**Comment by sabre1041** [comment]
Looks like the fix for the imagestream was implemented, however since the secret was added to the EAP STI a few days ago, it should be added to beta4 and backported for beta3.

https://github.com/jboss-openshift/application-templates/commit/7031996a91e9148392ca1e1e755f245285859918https://github.com/jboss-openshift/application-templates/commit/7031996a91e9148392ca1e1e755f245285859918

I can either make the changes to this PR or create new ones for beta3 and beta4

**Comment by thoraxe** [comment]
What's the change in the actual imagestream? The link above doesn't work.

**Comment by sabre1041** [comment]
Lets see if this prints out better

https://github.com/jboss-openshift/application-templates/commit/7031996a91e9148392ca1e1e755f245285859918

I am planning on rescinding this PR for beta3 to utilize a beta3 tag from the application-templates project that will utilize the correct EAP STI. This will avoid having to utilize the secrets. However, the imagestreams were changed in the training since the beta dropped. So those who pulled the repo when it dropped have outdated imagestream references. We can make a note in the EAP section to ensure they have the latest imagestreams added to OSE

**Comment by sabre1041** [comment]
Closing this PR and have opened new one to address beta3

https://github.com/openshift/training/pull/217

Continued discussions should take place on how to address EAP sti for beta4

**Pull request closed without merging**
