### PR TITLE
Improve registry deploy

### PR DESCRIPTION
**Pull request by sosiouxme**
Note the registry can take a while to come up.
Default for CONTAINER_ACCESSIBLE_API_HOST should work, don't confuse things by specifying it.

### CODE REVIEW

**Comment by thoraxe** [comment]
@sosiouxme  The reason I added that was because the default does not work in a 3-node environment that uses FQDN, per discussion with @smarterclayton 

I am pretty sure the default value will not work.

**Comment by smarterclayton** [comment]
The default containeraccessbilehost value is a bit of a hack - we need a stable address that is also signed by the root cert, and right now without internal DNS we don't have that.  So having the beta doc specify is ok - we should be sure customers know why

**Comment by sosiouxme** [comment]
Pretty sure the docker0 address is included in the master cert and thought that IP was considered stable enough for beta... will test how well it actually works when I get a chance. _shrug_ I guess if the fqdn works, then fine.

**Comment by smarterclayton** [comment]
It's stable enough for all-in-one and e2e tests.

----- Original Message -----

**Comment by thoraxe** [comment]
All I can say is that until I added the CONTAINER_ACCESSIBLE_API_HOST it didn't work -- especially if the registry didn't get deployed on the master.

**Comment by sosiouxme** [comment]
Alright, granted, I didn't know what I was talking about.

**Pull request closed without merging**
